<script setup lang="ts">
import { onBeforeUnmount, ref, watch } from "vue";
const dishes=[{no:"01",name:"炭烤春笋",en:"BAMBOO SHOOT",desc:"香椿 · 青花椒 · 松子",price:"68"},{no:"02",name:"茶熏桂鱼",en:"MANDARIN FISH",desc:"龙井 · 青梅 · 山芹",price:"168"},{no:"03",name:"菌菇小吊梨汤",en:"PEAR & MUSHROOM",desc:"羊肚菌 · 雪梨 · 陈皮",price:"58"}];
const menuOpen=ref(false),bookingOpen=ref(false),submitted=ref(false);
function openBooking(){menuOpen.value=false;submitted.value=false;bookingOpen.value=true} function closeBooking(){bookingOpen.value=false} function submitBooking(){submitted.value=true}
watch(bookingOpen,(value)=>{document.body.style.overflow=value?"hidden":""}); onBeforeUnmount(()=>{document.body.style.overflow=""});
</script>
<template><main><header class="site-header"><a class="brand" href="#top" aria-label="焰里首页"><span class="brand-mark">焰</span><span><b>焰里</b><small>YANLI</small></span></a><nav :class="['nav-links',{open:menuOpen}]" aria-label="主要导航"><a href="#story" @click="menuOpen=false">我们的故事</a><a href="#menu" @click="menuOpen=false">时令菜单</a><a href="#space" @click="menuOpen=false">空间</a><button class="mobile-book" @click="openBooking">预订餐位</button></nav><button class="book-link" @click="openBooking">预订餐位 <span>↗</span></button><button class="menu-toggle" aria-label="切换菜单" :aria-expanded="menuOpen" @click="menuOpen=!menuOpen"><i/><i/></button></header>
<section id="top" class="hero"><div class="hero-copy"><p class="eyebrow"><span/> 山野风物 · 当代东方</p><h1>山野入焰，<br/>四时成席。</h1><p class="hero-intro">寻味山林与河川，以火候唤醒当季风物。<br/>一席之间，尝见中国大地的温柔与丰盛。</p><div class="hero-actions"><button class="primary-btn" @click="openBooking">预订一席 <span>→</span></button><a class="text-link" href="#menu">品味本季菜单 <span>↘</span></a></div><div class="hours"><div><small>午市</small><b>11:30 — 14:00</b></div><div><small>晚市</small><b>17:30 — 22:30</b></div><div><small>地点</small><b>上海 · 武康路</b></div></div></div><div class="hero-art" aria-label="以山野食材为灵感的艺术餐盘"><div class="sun-orbit"/><div class="leaf leaf-a"><i/><i/><i/></div><div class="leaf leaf-b"><i/><i/><i/></div><div class="plate"><div class="plate-rim"/><div class="food food-a"/><div class="food food-b"/><div class="food food-c"/><span class="sauce sauce-a"/><span class="sauce sauce-b"/><span class="sauce sauce-c"/><div class="herb"><i/><i/><i/><i/></div></div><div class="season-card"><span>今 / 春</span><div><small>当季风味</small><strong>春山醒味</strong><p>八道式品鉴菜单</p></div><b>¥ 688</b></div><p class="art-caption">春笋 · 香椿 · 江鲜 · 新茶</p></div><a class="scroll-cue" href="#story"><span>SCROLL</span><i>↓</i></a></section>
<section id="story" class="story-section"><div class="section-label">01 / ABOUT YANLI</div><div class="story-title"><p>焰，唤醒食材的本味；<br/>里，安放一席相聚的心意。</p><h2>一口好味，<br/>总有它的来处。</h2></div><div class="story-grid"><div class="landscape-art"><span>雾</span><i/><b/></div><div class="story-copy"><p>我们顺着节气寻找食材。从山野的春笋、江河的鲜鱼，到一盏新茶，都在最合适的时候来到餐桌。</p><p>主厨林屿从熟悉的东方味道出发，以恰到好处的火候和当代手法，让食材自己说话，也让每一席饭吃得更有意思。</p><a href="#space">走进焰里 <span>→</span></a></div></div></section>
<section id="menu" class="menu-section"><div class="menu-heading"><div><p class="section-label">02 / SEASONAL MENU</p><h2>一季，一味。</h2></div><p>菜单随节气更迭。此刻的鲜美，<br/>错过便要再等一年。</p></div><div class="dish-list"><article v-for="dish in dishes" :key="dish.no" class="dish"><span>{{dish.no}}</span><div><h3>{{dish.name}}</h3><small>{{dish.en}}</small></div><p>{{dish.desc}}</p><b>¥ {{dish.price}}</b></article></div><button class="outline-btn" @click="openBooking">预订品鉴菜单 <span>↗</span></button></section>
<section id="space" class="space-section"><div class="space-art"><div class="window"><i/><i/><span/></div><p>光影、木石与一席烟火</p></div><div class="space-copy"><p class="section-label">03 / OUR SPACE</p><h2>留一方清静，<br/>慢慢吃一顿饭。</h2><p>空间取意江南庭院，木、石、纸与自然光彼此交叠。设有 42 个餐位及两间独立包厢，适合相聚，也容得下独处。</p><div class="contact-row"><span>上海市徐汇区武康路88号</span><span>021 6248 6688</span></div></div></section><footer><div class="footer-brand"><span class="brand-mark">焰</span><h2>焰里<small>YANLI</small></h2></div><p>把想说的话，<br/>留在这一席春光里。</p><div><button @click="openBooking">预订餐位 ↗</button><small>© 2026 YANLI RESTAURANT</small></div></footer>
<div v-if="bookingOpen" class="modal-backdrop" role="presentation" @mousedown.self="closeBooking"><section class="booking-modal" role="dialog" aria-modal="true" aria-labelledby="booking-title"><button class="close-modal" aria-label="关闭" @click="closeBooking">×</button><div v-if="submitted" class="success-state"><span>焰</span><h2>已为你留意</h2><p>我们将在 30 分钟内致电确认餐位。<br/>期待与你在焰里相见。</p><button @click="closeBooking">完成</button></div><template v-else><p class="eyebrow"><span/> RESERVATION</p><h2 id="booking-title">预订一席</h2><p>请留下用餐信息，我们会尽快与你确认。</p><form @submit.prevent="submitBooking"><label>称呼<input required placeholder="如何称呼你"/></label><div class="form-row"><label>日期<input required type="date"/></label><label>人数<select><option>1 位</option><option selected>2 位</option><option>3 位</option><option>4 位</option><option>5 位及以上</option></select></label></div><label>手机<input required type="tel" placeholder="用于确认餐位"/></label><button type="submit">提交预订 <span>→</span></button></form></template></section></div></main></template>
